In [43]:
#Import Libraries
import pandas as pd
#Read the excel file
dataset=pd.read_csv("insurance_pre.csv")
#data set is in categorical data- conver to numerical using dummies
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [45]:
#data set is in categorical data- conver to numerical using dummies
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [47]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [49]:
#Intependent variable Or input variable
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [51]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [53]:
#dependent variable  OR Output Variable
dependent=dataset["charges"]

In [55]:
#Train and Test(Split)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [73]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [75]:
#Model creation--------------------------------------------------TC1----------------------------------------------
from sklearn.svm import SVR
regressor=SVR(kernel="linear",gamma='scale',C=1.0)
regressor.fit(x_train,y_train)

SVR(kernel='linear')

In [77]:
#getting weight
weight=regressor.coef_
weight

array([[461.61813694,  56.54854763,  28.24973462,  14.00386876,
        472.37100882]])

In [79]:
#finding orgin value-how many support vector it has taken
regressor.intercept_

array([9445.22978805])

In [81]:
#predicting
y_pred=regressor.predict(x_test)

In [83]:
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [85]:
r_score

-0.010102665316081394

In [39]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

-0.010102665316081394

In [87]:
######################-------------------------------------------TC2-------------------------------------
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [89]:
#Model creation
from sklearn.svm import SVR
regressor=SVR(kernel="rbf",gamma='scale')
regressor.fit(x_train,y_train)

SVR()

In [91]:
#predicting
y_pred=regressor.predict(x_test)

In [93]:
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [95]:
r_score

-0.08338238593619329

In [105]:
#Model creation----------------------------------------------TC3-------------------------------------
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


from sklearn.svm import SVR
regressor=SVR(kernel="poly",gamma='scale')
regressor.fit(x_train,y_train)

SVR(kernel='poly')

In [107]:
#predicting
y_pred=regressor.predict(x_test)

In [109]:
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [111]:
r_score

-0.07569965570860893

In [113]:
#Model creation---------------------------------------TC4-----------------------------------------------
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


from sklearn.svm import SVR
regressor=SVR(kernel="sigmoid",gamma='scale')
regressor.fit(x_train,y_train)

SVR(kernel='sigmoid')

In [115]:
#predicting
y_pred=regressor.predict(x_test)

In [117]:
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [119]:
r_score

-0.07542924281107188

In [121]:
#Model creation-------------------------------------------TC5----------------------------------------------
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


from sklearn.svm import SVR
regressor=SVR(kernel="precomputed",gamma='scale')
regressor.fit(x_train,y_train)

ValueError: Precomputed matrix must be a square matrix. Input is a 936x5 matrix.

In [123]:
############for pre computed the dataset must be in mtrix formte so the error is thrown#######################33

In [125]:
#Model creation-----------------------------------------TC6-------------------------------------------
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


from sklearn.svm import SVR
regressor=SVR(kernel="linear",gamma='auto')
regressor.fit(x_train,y_train)

SVR(gamma='auto', kernel='linear')

In [127]:
#predicting
y_pred=regressor.predict(x_test)

In [129]:
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [131]:
r_score

-0.010102665316081394

In [133]:
#Model creation---------------------------------------------TC7-------------------------------------------------
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


from sklearn.svm import SVR
regressor=SVR(kernel="rbf",gamma='auto')
regressor.fit(x_train,y_train)

SVR(gamma='auto')

In [135]:
#predicting
y_pred=regressor.predict(x_test)

In [137]:
#validating
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

-0.08338238593619329

In [145]:
#Model creation-------------------------------------------TC8----------------------------------------------
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

from sklearn.svm import SVR
regressor=SVR(kernel="poly",gamma='auto')
regressor.fit(x_train,y_train)

SVR(gamma='auto', kernel='poly')

In [147]:
#predicting
y_pred=regressor.predict(x_test)

In [149]:
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

-0.07569965570860893

In [151]:
#Model creation----------------------------------------------------------TC9------------------------------------------
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

from sklearn.svm import SVR
regressor=SVR(kernel="sigmoid",gamma='auto')
regressor.fit(x_train,y_train)

SVR(gamma='auto', kernel='sigmoid')

In [141]:
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

-0.08338238593619329

In [143]:
#Model creation----------------------------------------------------------TC10------------------------------------------
from sklearn.svm import SVR
regressor=SVR(kernel="precomputed",gamma='auto')
regressor.fit(x_train,y_train)

ValueError: Precomputed matrix must be a square matrix. Input is a 936x5 matrix.

In [ ]:
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score