In [15]:
#Import Libraries
import pandas as pd

In [17]:
#Read the excel file
dataset=pd.read_csv("insurance_pre.csv")

In [19]:
#data set is in categorical data- conver to numerical using dummies
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [21]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [23]:
#Intependent variable Or input variable
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [25]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [27]:
#dependent variable  OR Output Variable
dependent=dataset["charges"]

In [29]:
#Train and Test(Split)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [30]:
#Model creation--------------------------------------------------TC1----------------------------------------------
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(n_estimators=10,max_features='sqrt',criterion='squared_error')
regressor.fit(x_train, y_train)

RandomForestRegressor(max_features='sqrt', n_estimators=10)

In [33]:
#predicting
y_pred=regressor.predict(x_test)

In [35]:
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [49]:
r_score

0.8454444839611641

In [37]:
##################################################TC2###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(n_estimators=100,max_features='sqrt',criterion='squared_error')
regressor.fit(x_train, y_train)

RandomForestRegressor(max_features='sqrt')

In [41]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8704721607468516

In [43]:
##################################################TC3###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='squared_error',max_features='log2',n_estimators=10)
regressor.fit(x_train, y_train)

RandomForestRegressor(max_features='log2', n_estimators=10)

In [45]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8480578745648906

In [47]:
##################################################TC4###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='squared_error',max_features='log2',n_estimators=100)
regressor.fit(x_train, y_train)

RandomForestRegressor(max_features='log2')

In [49]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8698690945212644

In [55]:
##################################################TC5###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='squared_error',max_features=None,n_estimators=10)
regressor.fit(x_train, y_train)

RandomForestRegressor(max_features=None, n_estimators=10)

In [57]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.845206993107888

In [59]:
##################################################TC6###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='squared_error',max_features=None,n_estimators=100)
regressor.fit(x_train, y_train)

RandomForestRegressor(max_features=None)

In [61]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8544007777355349

In [63]:
##################################################TC7###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='absolute_error',max_features='sqrt',n_estimators=10)
regressor.fit(x_train, y_train)

RandomForestRegressor(criterion='absolute_error', max_features='sqrt',
                      n_estimators=10)

In [65]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8558335587430352

In [67]:
##################################################TC8###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='absolute_error',max_features='sqrt',n_estimators=100)
regressor.fit(x_train, y_train)

RandomForestRegressor(criterion='absolute_error', max_features='sqrt')

In [69]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.873183055728207

In [79]:
##################################################TC9###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='absolute_error',max_features='log2',n_estimators=10)
regressor.fit(x_train, y_train)

RandomForestRegressor(criterion='absolute_error', max_features='log2',
                      n_estimators=10)

In [81]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8614455778461763

In [87]:
##################################################TC10###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='absolute_error',max_features='log2',n_estimators=100)
regressor.fit(x_train, y_train)

RandomForestRegressor(criterion='absolute_error', max_features='log2')

In [89]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8715855780375951

In [99]:
##################################################TC11###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='absolute_error',max_features=None,n_estimators=10)
regressor.fit(x_train, y_train)

RandomForestRegressor(criterion='absolute_error', max_features=None,
                      n_estimators=10)

In [101]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8370933155048447

In [107]:
##################################################TC12###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='absolute_error',max_features=None,n_estimators=100)
regressor.fit(x_train, y_train)

RandomForestRegressor(criterion='absolute_error', max_features=None)

In [109]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8522206119977125

In [111]:
##################################################TC13###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='friedman_mse',max_features='sqrt',n_estimators=10)
regressor.fit(x_train, y_train)

RandomForestRegressor(criterion='friedman_mse', max_features='sqrt',
                      n_estimators=10)

In [113]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.861257242120649

In [115]:
##################################################TC14###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='friedman_mse',max_features='sqrt',n_estimators=100)
regressor.fit(x_train, y_train)

RandomForestRegressor(criterion='friedman_mse', max_features='sqrt')

In [117]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8723554267301232

In [119]:
##################################################TC15###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='friedman_mse',max_features='log2',n_estimators=10)
regressor.fit(x_train, y_train)

RandomForestRegressor(criterion='friedman_mse', max_features='log2',
                      n_estimators=10)

In [121]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8517180586267574

In [127]:
##################################################TC16###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='friedman_mse',max_features='log2',n_estimators=100)
regressor.fit(x_train, y_train)

RandomForestRegressor(criterion='friedman_mse', max_features='log2')

In [129]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.868434226683466

In [131]:
##################################################TC17###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='friedman_mse',max_features=None,n_estimators=10)
regressor.fit(x_train, y_train)

RandomForestRegressor(criterion='friedman_mse', max_features=None,
                      n_estimators=10)

In [133]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8440350828530628

In [139]:
##################################################TC18###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='friedman_mse',max_features=None,n_estimators=100)
regressor.fit(x_train, y_train)

RandomForestRegressor(criterion='friedman_mse', max_features=None)

In [141]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8535590092291206

In [143]:
##################################################TC19###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='poisson',max_features='sqrt',n_estimators=10)
regressor.fit(x_train, y_train)

RandomForestRegressor(criterion='poisson', max_features='sqrt', n_estimators=10)

In [145]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8538385418527424

In [147]:
##################################################TC20###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='poisson',max_features='sqrt',n_estimators=100)
regressor.fit(x_train, y_train)

RandomForestRegressor(criterion='poisson', max_features='sqrt')

In [149]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8707483938351135

In [153]:
##################################################TC21###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='poisson',max_features='log2',n_estimators=10)
regressor.fit(x_train, y_train)

RandomForestRegressor(criterion='poisson', max_features='log2', n_estimators=10)

In [155]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8571951329866405

In [157]:
##################################################TC22###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='poisson',max_features='log2',n_estimators=100)
regressor.fit(x_train, y_train)

RandomForestRegressor(criterion='poisson', max_features='log2')

In [159]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8710498834924851

In [161]:
##################################################TC23###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='poisson',max_features=None,n_estimators=10)
regressor.fit(x_train, y_train)

RandomForestRegressor(criterion='poisson', max_features=None, n_estimators=10)

In [163]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8314359723618139

In [165]:
##################################################TC24###########################################################
#Model Creation
from sklearn.ensemble import RandomForestRegressor
regressor= RandomForestRegressor(criterion='poisson',max_features=None,n_estimators=100)
regressor.fit(x_train, y_train)

RandomForestRegressor(criterion='poisson', max_features=None)

In [167]:
#predicting
y_pred=regressor.predict(x_test)
#validating
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)
r_score

0.8536427061146106